### ISSUE TITLE
get_or_* method's trait bound is too strict .

### ISSUE THREAD

**Issue by Liyixin95** [arthurprs/quick-cache#10]
# Problem Description

consider we have a cache like this:

```rust
let cache = Arc::new(sync::Cache::<String, u64>::new(100));
```

if i call get_value_or_guard like this: 

```rust
cache.get_value_or_guard("foo", None);
```

then i get a compile error:

```
error[E0308]: mismatched types
   --> src\lib.rs:389:34
    |
389 |         cache.get_value_or_guard("foo", None);
    |               ------------------ ^^^^^ expected `&String`, found `&str`
    |               |
    |               arguments to this method are incorrect
    |
    = note: expected reference `&std::string::String`
               found reference `&'static str`
note: method defined here
   --> src\sync.rs:304:12
    |
304 |     pub fn get_value_or_guard<'a>(
    |            ^^^^^^^^^^^^^^^^^^
305 |         &'a self,
306 |         key: &Key,
    |         ---------
```

So, I have to clone the key, which is unnecessary.

# Possible Solution

Maybe we can use ToOwned instead of Clone, like this:

```
    pub async fn get_value_or_guard_async<Q>(
        &self,
        key: &Q,
    ) -> Result<Val, PlaceholderGuard<'_, Key, Val, We, B, L>>
    where
        Q: Hash + Equivalent<Key> + ToOwned<Owned = Key> + ?Sized,
```

ToOwned is implement for all T that implement Clone: 

```rust
impl<T> ToOwned for T
where
    T: Clone,
```

So, this trait bound is compatible with the old one, and allow more key type, such as &str for String.

Finally, thanks for creating this great crate, and I would like to provide a pr for this issue, if you agree with this solution.

**Comment by arthurprs** [comment]
Hi, thank you for creating the issue.

I remember this problem when I was writing the API. I couldn't find a solution that prevented a clone in all situations.

For example, `: ToOwned` allows preventing a clone when the get is successful, but it'll also cause all keys to be "cloned" if missing, even if you had `String` in hand.

That said, generating a `V` on a "miss path" is probably going to be much more expensive than cloning `K`. I think the ToOwned solution makes sense in most cases and I'd welcome such PR :+1:
