### ISSUE TITLE
Is estimated_items_capacity superfluous in Cache::with_weighter?

### ISSUE THREAD

**Issue by marvin-j97** [arthurprs/quick-cache#17]
Hi,

I've been using `quick-cache` inside https://github.com/marvin-j97/lsm-tree with great success so far. I've recently been changing from `Cache::new` to `Cache::with_weighter`.

Is there any expected changes in performance when changing `estimated_items_capacity`? According to my benchmarks this value does not change insert performance nor retrieval performance. So what is the difference between
- `Cache::with_weighter(0, 1_000_000, w)` and
- `Cache::with_weighter(1, 1_000_000, w)` and
- `Cache::with_weighter(1_000_000, 1_000_000, w)`, if any?

Both caches are supposed to store 1'000'000 bytes (or whatever unit the weighter returns).

**Comment by arthurprs** [comment]
Hi, you have cool project in lsm-tree!

It's almost superfluous, but the estimated capacity is still used to estimate the size of the non-resident (aka. ghost) list and minimum number of shards. The former may affect hit-ratio depending on the recency/frequency bias of the workload.

**Comment by marvin-j97** [comment]
Will the cache balance over time? So if my estimation is bad, will I pay the penalty forever, or is it not important as the capacity fills up?

**Comment by arthurprs** [comment]
Not right now, the ghost capacity is set at creation time and never adjusted. That could be improved, though.

**Comment by arthurprs** [comment]
> or is it negligible as the capacity fills up?

I forgot to answer this part. In the majority of cases, it's indeed negligible. Unless the Key/value size is very small, which is rare in practice, specially in a database.

**Comment by marvin-j97** [comment]
I'm guessing setting it too high is negligible too in terms of memory usage?
Pre-setting it with 10k * 4 KiB doesn't allocate 40 MB, so that's good.

**Comment by arthurprs** [comment]
Correct. Ghost entries only occupy hashtable size, they don't hold actual Key or Value types. I assume your keys and values are a `Vec<u8>` (or a similar sized type), so the space consumed by them will be tiny.
