### ISSUE TITLE
Clear all items from `sync::Cache`

### ISSUE THREAD

**Issue by LafeWessel** [arthurprs/quick-cache#19]
The `unsync::Cache` has a `clear()` method that will remove all the items in the cache. However, the `sync::Cache` does not have an equivalent function. It would be very nice to have `fn clear(&self)` for the `sync::Cache` for clearing all entries from the cache without having to drop the previous cache and replace it with a new one to ensure that all the items have been cleared out of it.

**Comment by arthurprs** [comment]
It's implemented but not released https://github.com/arthurprs/quick-cache/commit/d1c7d96811eb4dd318857a6bd943c7f027469380

I'll try to cut a release soon.

**Comment by 0xdeafbeef** [comment]
@arthurprs sorry for ping, how is it going?

**Comment by arthurprs** [comment]
Sorry for the delay.

I just published v0.4.1, which contains the clear function for the sync cache.
