### ISSUE TITLE
`unsync::Cache::get_or_insert_with`

### ISSUE THREAD

**Issue by nagisa** [arthurprs/quick-cache#21]
Currently in order to implement "if missing, insert & return the value from the cache" with `unsync::Cache` it is necessary to do something like this:

```
if let Some(val) = cache.get(key) { return val; }
cache.insert(key, with());
cache.get(key).unwrap()
```

however this ends up pushing an assumption that `Cache::insert` can't fail, for instance, and forces three total lookups of the key.

I have taken a look at implementing this myself, but this seems quite involved. In particular, `Shard::insert` has multiple strategies it works with and it won't necessarily insert the value into the cache due to weight limits, at which point it might give away the ownership to the lifecycle management hook. So it returns a `Result<(), (Key, Val)>`.

But maybe there's still a way that I'm not seeing to enable it returning `&Val` upon successful insertion?

**Comment by arthurprs** [comment]
Yeah, allowing the cache to be overweight might have large implications.

If we ignore that part, I could probably add support for `get_or_insert` to return a `Option<&mut V>` kind of thing w/o extra lookups.

**Comment by nagisa** [comment]
Even just `insert` returning a `Result<&mut V, V>` would work for pretty much everything in my case. Basically either V is in the cache and I can refer to it that way, or it was not inserted for any reason, in which case I can still grab a reference of the value and do something with it without duplicating the effort to regenerate it.

But that would require not calling `on_evict` if the item hasn't actually been inserted into the cache.

Thanks for the quick response.

**Comment by arthurprs** [comment]
I tried to add APIs that would satisfy your use case, but it's elusive to get it to co-exists with the lifecycle hooks. It might take another round of refactors to get it right.

Can you check if https://github.com/arthurprs/quick-cache/blob/74aeb9ec09e9dddf96edfc9e276342577450000f/src/unsync.rs#L248 or one of the new apis improve your use case?

**Comment by nagisa** [comment]
I think I could implement what I need with `get_mut_or_guard`. `get_mut_or_insert_with`, as far as I understand would require me to duplicate the logic acting on the value if I wanted to do something with it regardless of whether the value was able to make it into the cache or not. Something like this perhaps:

```
let already_used = false;
value = cache.get_mut_or_insert_with(key, || {
    let mut value = generate();
    already_used = true;
    use(&mut value);
    value
});
if !already_used {
    use(&mut value);
}
```

Not too terrible, I guess? Though in this particular use it would perhaps be better if `get_mut_or_insert_with` either invoked the callback XOR returned a reference, not potentially both. That would allow dropping the `already_used` type of flag.

**Comment by nagisa** [comment]
Thanks for responding so quickly and spending your time on implementing this! Much appreciated!

**Comment by arthurprs** [comment]
I merged https://github.com/arthurprs/quick-cache/pull/23 on `master` now, I'll keep the issue open until I make a crates.io release with it.

**Comment by arthurprs** [comment]
0.5 has now been published
