### ISSUE TITLE
Bug: soft = true changes entry hotness, as opposed to documented

### ISSUE THREAD

**Issue by jon-chuang** [arthurprs/quick-cache#33]
If soft is true, match will fail, predicate is true, so evaluates to referenced += 1.

But soft = true is stated not to change hotness

https://github.com/arthurprs/quick-cache/blob/10cd51bd97f66cb08a6f3305756544a670a4e796/src/shard.rs#L659

Solution:

```diff
- !matches!
+ matches!
```

**Comment by arthurprs** [comment]
:eagle::eye:, do you want to submit a PR for this?
