### ISSUE TITLE
Bug: `Cache.reserve` does not need mutable ref

### ISSUE THREAD

**Issue by jon-chuang** [arthurprs/quick-cache#34]
https://github.com/arthurprs/quick-cache/blob/10cd51bd97f66cb08a6f3305756544a670a4e796/src/sync.rs#L213

shards are behind rwlock

https://github.com/arthurprs/quick-cache/blob/10cd51bd97f66cb08a6f3305756544a670a4e796/src/sync.rs#L217

**Comment by arthurprs** [comment]
Indeed, do you want to submit a PR for this?
