### ISSUE TITLE
Re-add `.hits()` and `.misses()` to `sync::Cache`

### ISSUE THREAD

**Issue by LafeWessel** [arthurprs/quick-cache#37]
Unless I'm blind (which is very possible) the `.hits()` and `.misses()` functions were removed from the `sync::Cache`. It would be nice to have them back for internal logging and testing without messing around with wrapping the cache accesses with Atomics or some other method of tracking those metrics.

**Comment by arthurprs** [comment]
They're there, but in the last version they were moved behind the "stats" feature. I realized thought that docs.rs isn't displaying these functions, so discoverability is bad. I'm going to try and fix that.
