### ISSUE TITLE
Add atomic `get_or_insert` method to sync `Cache`/`KQCache`

### ISSUE THREAD

**Issue by AlexTMjugador** [arthurprs/quick-cache#4]
Hi! Thank you for your work on this lightweight, versatile Rust cache library :smile: 

I'd like to use it to implement a cache for deserialized file data that multiple threads can access in parallel. Roughly, I'd like each thread to interact with the cache like this:

- The thread asks the cache whether the data for a file has been deserialized (i.e., calls `get` on the cache).
  - If deserialized data is cached (i.e., `get` returns `Some`), then use that to do work.
  - If the deserialized data is not cached (i.e., `get` returns `None`), then deserialize it, add it to the cache (i.e., call `insert`), and use the just deserialized data.

However, implementing that with the currently available API is unsatisfactory:

- Using `get` and `insert` naively means that there is the possibility that several threads watch `get` yielding `None`, so data may be deserialized several times, only to have most of that work discarded when the thread that finishes last calls `insert`. This does not affect correctness in my case, but can waste a lot of work.
- Alternatively, the unsynchronized versions of `Cache`/`KQCache` can be used in conjunction with external synchronization, so that each thread acquires a mutex before calling the `get` and `insert` methods of the cache. This guarantees the atomicity of both operations and that no other thread will see the missing cache entry while data is being deserialized, but introduces a lot of contention.

As an ideal solution to this situation, I'd like the API of this crate to provide an atomic `get_or_insert_with` method, [similar to that of the `Entry` enum in the Rust standard library](https://doc.rust-lang.org/std/collections/hash_map/enum.Entry.html#method.or_insert_with), that allows this atomic read-compute a value-insert operation to be performed as efficiently as possible.

**Comment by arthurprs** [comment]
Thank you for creating the issue. I think that would be a good feature in general. I'll try to come up with something that doesn't affect the lightweight design goal, but the timeline is unknown.

**Comment by AlexTMjugador** [comment]
That's great to hear, thanks! :heart:

What's left to do for the changes to be considered stable? I could try them out and give feedback if that'd be useful.

**Comment by arthurprs** [comment]
I need to give for my brain to reset, so I can review the implementation before releasing.

If you have the opportunity to play with it, that would be great!

**Comment by AlexTMjugador** [comment]
I had some time to play around with these changes yesterday. They worked pretty well, and they improved performance as expected. Thanks! :heart:
