### ISSUE TITLE
Eviction with hierarchical keys

### ISSUE THREAD

**Issue by marvin-j97** [arthurprs/quick-cache#46]
:wave: It's the LSM-tree guy again.

I've seen that QC supports a clear method, however I find that pretty destructive for my use case. As is typical with an LSM-tree, sometimes some parts of the database may be nuked after compaction, so a bunch of entries in the cache will be useless. Of course, they will get replaced over time; but only if the cache limit is actually eventually reached.

Consider a cache capacity of 1GB and a database of size 500MB.
As data is written and compacted down the levels, the cache will fill up, to let's say 500 MB. Now, when a compaction creates new segments further down the tree and nukes the old segments, the cache capacity is not reduced, but the new segments will take more cache size, surpassing 500 MB, up to 1 GB. This makes it impossible to configure the cache optimistically. If 2 GB are stored, and the cache capacity is 8 GB, over time the cache is likely to take 8 GB, so 6 GB of the cache will be dead data nobody will ever read again.
Especially, in a key-value separated tree, the index tree is pretty small (e.g. 30 MB), but setting the cache to something like 50 MB may require manual monitoring and adjusting of the cache size, when eventually it grows past 50 MB. And setting it to 1 GB will eat away the memory, even though just 30-50 MB would be needed. Even being pessimistic and setting it to 200 MB would use 150MB more than needed.

---

The block cache uses weighted entries and, more importantly, hierarchical keys that look like this:
(tree id) -> (segment id) -> (offset)

So if segment 4 in tree 0 is deleted, I would like to evict all cache entries that match
(0) -> (4) -> *

Could QC support a retain() method that allows partially clearing the cache?
This process doesn't happen too often and happens asynchronously, but I can imagine for a huge GB-sized cache it can still have quite some overhead, as I understand it will have to go through all shards.
Would it be advantageous to adjust the hash to partition a segment's entries to the same shard (so just hashing [tree ID, segment ID], instead of [tree ID, segment ID, offset]) - that would cut down the cleanup process to 1 shard only, but it would need some API so the retain is concentrated on just 1 shard (it would need the hash...).

Does this make sense?

Edit: I guess this probably doesn't work because the same hash is used for the HashBrown table... there would need to be 2 hashes, a partitioning/shard hash and the item hash...?

![image](https://github.com/user-attachments/assets/e9678b40-7092-4fbb-9ac8-91849cba18f2)

**Comment by arthurprs** [comment]
I think QuickCache can do little natively other than provide `retain` and maybe `deprioritize`. Retain uses a write lock on each shard and works intuitively, as you'd expect. Deprioritize scans the cache and deprioritizes entries, so they're much more likely to be evicted. The difference is that this one can operate with a read lock.

You could try adding a second level of sharding/partitioning so you have many read caches, but each partition can only get so big. I don't think this is desirable.

Btw, what software do you use for your diagrams?

**Comment by marvin-j97** [comment]
> I think QuickCache can do little natively other than provide `retain` and maybe `deprioritize`. Retain uses a write lock on each shard and works intuitively, as you'd expect. Deprioritize scans the cache and deprioritizes entries, so they're much more likely to be evicted. The other difference is that deprioritize can operate with a read lock, so reads still go through.

Hmm, retain may work, I don't know how expensive it will be though. Considering it write locks one shard at a time, it may not be too bad, but it will probably still have to iterate through a bunch of stuff.
Maybe I'll see if I can come with something in a fork...

> You could try adding a second level of sharding/partitioning so you have many block caches, but each partition can only get so big. I don't think this is desirable.

Yeah, that adds another RwLock into the hot path which I want to avoid.

> Btw, what software do you use for your diagrams?

Excalidraw

**Comment by arthurprs** [comment]
> > You could try adding a second level of sharding/partitioning so you have many block caches, but each partition can only get so big. I don't think this is desirable.
> 
> Yeah, that adds another RwLock into the hot path which I want to avoid.
> 

Not necessarily; once you build a `Arc<Vec<QuickCache>>` you can access it w/o a RwLock. You can route requests to them based on their segment ID hashed. No rwlock involved. Then you'd only have to call retain/deprioritize on the shard responsible for that segment.

**Comment by marvin-j97** [comment]
> Not necessarily; once you build a `Arc<Vec<QuickCache>>` you can access it w/o a RwLock. You can route requests to them based on their segment ID hashed. No rwlock involved. Then you'd only have to call retain/deprioritize on the shard responsible for that segment.

Hmm yeah that's true, I was thinking of a hash map. No matter what, retain would be needed anyway. Not sure if manually partitioning is worth it, I would have to benchmark that, but any kind of garbage collection would be better than none.

**Comment by marvin-j97** [comment]
Moka seems to support "retain", by using "invalidate_entries_if".

**Comment by marvin-j97** [comment]
I may just merge both caches into a single one. That would kind of solve the issue, because everything is capped by a single capacity limit. My thinking was that two tiers may be beneficial because the smaller cache (for blocks) should ideally be fully cached, while the larger cache (for blobs) will probably never fully fit in RAM, so each item is quite expensive and it would be detrimental to lose an item in the small cache.

But ideally a single cache with its hot/cold tier and eviction logic should be smart enough... does the size affect eviction chances or is it only there to limit the capacity?

@arthurprs

**Comment by arthurprs** [comment]
More capacity can be expected to lead to higher hit rates (less evictions).

I think an unified cache is probably near optimal all other things being equal.

**Comment by arthurprs** [comment]
Closing the issue for now, let me know if I can be of assistance.
