### ISSUE TITLE
Replace sometime evicts the replaced entry

### ISSUE THREAD

**Issue by EtienneDx** [arthurprs/quick-cache#50]
When replacing an entry, it sometimes get evicted if the new value makes it go over the size limit. I'd expect other entries to be evicted first.

**Comment by arthurprs** [comment]
I believe that's possible, yes. This is because there are various levels of "hotness" in the cache, and replacing an entry will bump the existing entry's hotness by one level. If all other entries were at a level above, the replaced entry would still be the lowest.

Do you need specific items to be in the cache after insertion? That usually takes some effort. If you describe your use case I might be able to suggest something.

**Comment by EtienneDx** [comment]
Simplest test I have with a max_weight of 10:
- Add an object, modify it to size 5
- Add an object, modify it to size 2
- Add an object, modify it to size 4
Without any read, I expected the latest modify to be in the cache. My tests give me a cache size of 7 and the 4th object isn't in the cache, right after I added it.
Basically I think when calling modify (insert_existing), it should be impossible for the modified object to be evicted.

**Comment by arthurprs** [comment]
> Basically I think when calling modify (insert_existing), it should be impossible for the modified object to be evicted.

I think only an LRU cache would really guarantee that behavior (which usually leads to worse hit ratios).

Other algorithms might still think the replaced keys are less useful. I'm trying to ascertain whether your case is indeed that or a bug.

I attempted to reproduce with your description but couldn't

```rust
    impl Weighter<u32, u32> for U32Weighter {
        fn weight(&self, _key: &u32, val: &u32) -> u64 {
            *val as u64
        }
    }

    #[test]
    fn issue_50() {
        let mut c = unsync::Cache::with_weighter(5, 10, U32Weighter);
        c.insert(1, 1);
        c.replace(1, 5, false).unwrap();
        c.insert(2, 1);
        c.replace(2, 2, false).unwrap();
        c.insert(3, 1);
        c.replace(3, 4, false).unwrap();
        dbg!(c.len(), c.weight());
    }
```

**Comment by EtienneDx** [comment]
I'm looking into a simpler way to reproduce, I've been using the sync version and quite a few wrappers so I don't have it on hand. Will let you know if I manage to reproduce easily.

**Comment by EtienneDx** [comment]
Finally got it:
```rust
    #[test]
    fn issue_50_bis() {
        let c = quick_cache::sync::Cache::with_weighter(5, 10, U32Weighter);

        c.insert(1, 1);
        c.replace(1, 5, true).unwrap();
        c.get(&1).expect("Replaced value should be set");

        c.insert(2, 1);
        c.replace(2, 2, true).unwrap();
        c.get(&2).expect("Replaced value should be set");

        c.insert(3, 1);
        c.replace(3, 4, true).unwrap();
        c.get(&3).expect("Replaced value should be set");

        dbg!(c.len(), c.weight());  // 2, 6
        assert_eq!(c.len(), 2);
        assert_eq!(c.weight(), 6);
    }
    ```

Now that I finally pinpointed it, it seems the `get` and the `soft: true` are the reason. I'm guessing that's a feature and not a bug then? ...

**Comment by arthurprs** [comment]
`soft=false` will cause the cache to not touch the key "hotness", so yeah, it seems to be working as intended.

**Comment by EtienneDx** [comment]
Just to confirm, it is safe to assume that with `soft=false`, the item will *always* be in the cache, which is not the case with `soft=true`, right? If so I guess this ticket can be closed.

**Comment by arthurprs** [comment]
Even with soft=false, I can probably come up with an example where it isn't if the new item has more weight than the previous, but it's a lot less likely in practice.

Depending on your use case you may want to look into [Pinning](https://docs.rs/quick_cache/latest/quick_cache/trait.Lifecycle.html#method.is_pinned)
