### ISSUE TITLE
is there a delete or remove function?

### ISSUE THREAD

**Issue by kolinfluence** [arthurprs/quick-cache#54]
as titled

**Comment by LafeWessel** [comment]
If you read the [documentation](https://docs.rs/quick_cache/0.6.9/quick_cache/), you'll find that there are `remove` functions on the caches.

https://docs.rs/quick_cache/0.6.9/quick_cache/sync/struct.Cache.html#method.remove
https://docs.rs/quick_cache/0.6.9/quick_cache/unsync/struct.Cache.html#method.remove
