### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by ahrens** [arthurprs/quick-cache#7]
I've noticed a few problems with the documentation:

In [quick_cache::sync::Cache](https://docs.rs/quick_cache/0.2.4/quick_cache/sync/struct.Cache.html):

get():
> Callers should prefer get_mut whenever possible as it’s more efficient

There's no get_mut method

remove():
> Peeks an item from the cache whose key is key and qey is <= highest_version. Contrary to gets, peeks don’t alter the key “hotness”.

There's no `qey`.  This is not peek.

insert():
> Inserts an item in the cache with key key and qey qey.

There's no `qey`.

[OptionsBuilder](https://docs.rs/quick_cache/0.2.4/quick_cache/struct.OptionsBuilder.html):

build():
> Panics if weight_capacity or estimated_items_capacity were not set.

From looking at the code, this doesn't seem true, it returns an error.

**Comment by arthurprs** [comment]
Thank you for pointing these out. Fell free to open a PR, otherwise I'll try to get to them before the next release.
